export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: '登录',
        path: '/user/login',
        component: './user/Login',
      },
      {
        name: '注册',
        icon: 'smile',
        path: '/user/register',
        component: './user/Register',
      },
      {
        name: '注册结果',
        icon: 'smile',
        path: '/user/register/result',
        component: './user/Register/RegisterResult',
      },
      {
        name: '退出登录',
        icon: 'smile',
        path: '/user/logout',
        component: './user/Logout',
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/student/info',
    name: '个人主页',
    icon: 'smile',
    component: './student/Information',
    access: 'canStudent',
  },
  {
    name: '模拟考试',
    icon: 'smile',
    path: '/student/exam',
    component: './student/Exam',
    access: 'canStudent',
  },
  {
    name: '题库学习',
    icon: 'smile',
    path: '/student/test',
    component: './student/Test',
    access: 'canStudent',
  },
  {
    path: '/student/test/practice',
    component: './student/Test/Practice',
    access: 'canStudent',
  },
  {
    name: '查看错题',
    icon: 'smile',
    path: '/student/mistake',
    component: './student/Mistake',
    access: 'canStudent',
  },
  {
    name: '查看成绩',
    icon: 'smile',
    path: '/student/chart',
    component: './student/Chart',
    access: 'canStudent',
  },
  {
    name: '公告提示',
    icon: 'smile',
    path: '/student/notice',
    component: './student/Notice',
    access: 'canStudent',
  },
  {
    name: '反馈投诉',
    icon: 'smile',
    path: '/student/feedback',
    component: './student/Feedback',
    access: 'canStudent',
  },
  {
    path: '/student/exam/exampage',
    component: './student/Exam/ExamPage',
    access: 'canStudent',
  },
  {
    path: '/student/exam/startexam',
    component: './student/Exam/StartExam',
    access: 'canStudent',
  },
  {
    path: '/student/exam/result',
    component: './student/Exam/ExamResult',
    access: 'canStudent',
  },
  {
    path: '/coach/info',
    name: '个人主页',
    icon: 'smile',
    component: './coach/Information',
    access: 'canCoach',
  },
  {
    name: '考试题库',
    icon: 'smile',
    path: '/coach/upload',
    component: './coach/UpExam',
    access: 'canCoach',
  },
  {
    name: '学习题库',
    icon: 'smile',
    path: '/coach/uptest',
    component: './coach/UpTest',
    access: 'canCoach',
  },
  {
    name: '考试修改',
    icon: 'smile',
    path: '/coach/revise',
    component: './coach/Revise',
    access: 'canCoach',
  },
  {
    name: '学习修改',
    icon: 'smile',
    path: '/coach/study',
    component: './coach/Study',
    access: 'canCoach',
  },
  {
    name: '学员成绩',
    icon: 'smile',
    path: '/coach/score',
    component: './coach/Score',
    access: 'canCoach',
  },
  {
    name: '投诉箱',
    icon: 'smile',
    path: '/admin/receive/feedback',
    component: './admin/Refeed',
    access: 'canAdmin',
  },
  {
    name: '发布公告',
    icon: 'smile',
    path: '/admin/upnotice',
    component: './admin/UpNotice',
    access: 'canAdmin',
  },
  {
    name: '学员管理',
    icon: 'smile',
    path: '/admin/userlist',
    component: './admin/UserList',
    access: 'canAdmin',
  },
  {
    name: '教练管理',
    icon: 'smile',
    path: '/admin/coachlist',
    component: './admin/CoachList',
    access: 'canAdmin',
  },
  {
    name: '退出登录',
    icon: 'LogoutOutlined',
    path: '/user/logout',
    component: './user/Logout',
  },
];
